FROM python:3.9-slim

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install venv and create a virtual environment
RUN python -m venv venv

# Install dependencies using the virtual environment's pip
RUN /app/venv/bin/pip install --upgrade pip && \
    /app/venv/bin/pip install --no-cache-dir flask

# Make port 5000 available to the world outside this container
EXPOSE 5000

# Define environment variable
ENV NAME World

# Use the virtual environment's Python interpreter to run the app
CMD ["/app/venv/bin/python", "app.py"]